### ISSUE TITLE
Remove repeated code in notebooks

### ISSUE THREAD

**Issue by ishandandekar** [Harshjain2707/Dream11_Points_Prediction#1]
Notebooks [Model_with_5_features.ipynb](https://github.com/Harshjain2707/Dream11_Points_Prediction/blob/main/Notebooks/Model_with_5_features.ipynb) and [Model_with_2_features.ipynb](https://github.com/Harshjain2707/Dream11_Points_Prediction/blob/main/Notebooks/Model_with_2_features.ipynb) have repeated code of comparing models. This can be removed by using the function only once. If needed I can create a PR

**Comment by Harshjain2707** [comment]
Yeah please go ahead. Thank you!
